/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package View;

import Model.Graph;
import java.util.List;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import sl.city.distance.calculator.SLCityDistanceCalculator;

/**
 *
 * @author Shahe
 */
public class InternalHome extends javax.swing.JInternalFrame {

    Graph graph = new Graph();

    /**
     * Creates new form InternalHome
     */
    public InternalHome() {
        initComponents();
        lbl_path.setVisible(false);

        txt_mindistance.setEditable(false);

        cmb_startcity.removeAllItems();
        cmb_destinationcity.removeAllItems();

        cmb_startcity.addItem("--Select--");
        cmb_destinationcity.addItem("--Select--");

        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI bi = (BasicInternalFrameUI) this.getUI();
        bi.setNorthPane(null);

        txt_allPaths.setVisible(false);
        txt_allPaths.setEditable(false);

        List<String> vertices = graph.getVertices();
        for (String vertex : vertices) {
            cmb_startcity.addItem(vertex);
            cmb_destinationcity.addItem(vertex);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cmb_startcity = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        cmb_destinationcity = new javax.swing.JComboBox<>();
        btn_search = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txt_mindistance = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        check_routes = new javax.swing.JCheckBox();
        lbl_path = new javax.swing.JLabel();
        jp_map = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_allPaths = new javax.swing.JTextArea();

        setPreferredSize(new java.awt.Dimension(1193, 934));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(1181, 934));

        jLabel1.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jLabel1.setText("Select Starting City");

        cmb_startcity.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        cmb_startcity.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Select City--", "Colombo", "Galle", "Horana", "Jaffna", "Kandy", "Panadura", " ", " " }));

        jLabel2.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jLabel2.setText("Select Destination City");

        cmb_destinationcity.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        cmb_destinationcity.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Select City--", "Colombo", "Galle", "Horana", "Jaffna", "Kandy", "Panadura" }));

        btn_search.setBackground(new java.awt.Color(0, 153, 0));
        btn_search.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        btn_search.setForeground(new java.awt.Color(255, 255, 255));
        btn_search.setText("Search");
        btn_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_searchActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jLabel3.setText("Minimum Travel Distance");

        txt_mindistance.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        txt_mindistance.setDisabledTextColor(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jLabel4.setText("Shortest Path");

        check_routes.setBackground(new java.awt.Color(255, 255, 255));
        check_routes.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        check_routes.setText("Show optional routes");
        check_routes.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                check_routesStateChanged(evt);
            }
        });
        check_routes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check_routesActionPerformed(evt);
            }
        });

        lbl_path.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        lbl_path.setText("Path");

        jp_map.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/map_480x601.jpg"))); // NOI18N

        javax.swing.GroupLayout jp_mapLayout = new javax.swing.GroupLayout(jp_map);
        jp_map.setLayout(jp_mapLayout);
        jp_mapLayout.setHorizontalGroup(
            jp_mapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_mapLayout.createSequentialGroup()
                .addContainerGap(75, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(46, 46, 46))
        );
        jp_mapLayout.setVerticalGroup(
            jp_mapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_mapLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel5))
        );

        txt_allPaths.setColumns(20);
        txt_allPaths.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        txt_allPaths.setRows(5);
        jScrollPane1.setViewportView(txt_allPaths);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(12, 12, 12)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_mindistance, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(cmb_startcity, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(29, 29, 29)
                                        .addComponent(jLabel2)
                                        .addGap(90, 90, 90)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(check_routes)
                                            .addComponent(cmb_destinationcity, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addComponent(btn_search, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lbl_path, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jp_map, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(248, 248, 248))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cmb_destinationcity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_search)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(cmb_startcity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_mindistance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_path, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(check_routes)
                        .addGap(22, 22, 22)
                        .addComponent(jScrollPane1))
                    .addComponent(jp_map, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(82, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_searchActionPerformed

        if (cmb_startcity.getSelectedIndex() == 0 || cmb_destinationcity.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null, "Please select both Start and Destination cities.","Error",JOptionPane.ERROR_MESSAGE);
        } else {
            List<String> paths = graph.shortestPath(cmb_startcity.getSelectedItem().toString(), cmb_destinationcity.getSelectedItem().toString());
            int distance = graph.shortestDistance(cmb_startcity.getSelectedItem().toString(), cmb_destinationcity.getSelectedItem().toString());
            String label = "";
            if (distance < 0 || distance > 2000) {
                lbl_path.setText("Destination is unreachable from Source");
                lbl_path.setVisible(true);
            } else {
                for (String path : paths) {
                    label += "  =>  ";
                    label += path;
                }

                txt_mindistance.setText(String.valueOf(distance) + " km");

                lbl_path.setText(label);
                lbl_path.setVisible(true);
            }
        }
    }//GEN-LAST:event_btn_searchActionPerformed

    private void check_routesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check_routesActionPerformed

    }//GEN-LAST:event_check_routesActionPerformed

    private void check_routesStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_check_routesStateChanged
        if (check_routes.isSelected()) {
             if (cmb_startcity.getSelectedIndex() == 0 || cmb_destinationcity.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null, "Please select both Start and Destination cities.","Error",JOptionPane.ERROR_MESSAGE);
        } else {
            Map<List<String>, Integer> allPaths = graph.getAllPaths(cmb_startcity.getSelectedItem().toString(), cmb_destinationcity.getSelectedItem().toString());
            StringBuilder sb = new StringBuilder();

            for (Map.Entry<List<String>, Integer> entry : allPaths.entrySet()) {
                
                for(String path : entry.getKey())
                {
                        sb.append(" => ").append(path);
                }
                
                sb.append(" : ").append(entry.getValue()).append(" km \n");
            }

            txt_allPaths.setText(sb.toString());
            txt_allPaths.setVisible(true);
             }
        } else {
            txt_allPaths.setText("");
            txt_allPaths.setVisible(false);

        }
    }//GEN-LAST:event_check_routesStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_search;
    private javax.swing.JCheckBox check_routes;
    private javax.swing.JComboBox<String> cmb_destinationcity;
    private javax.swing.JComboBox<String> cmb_startcity;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jp_map;
    private javax.swing.JLabel lbl_path;
    private javax.swing.JTextArea txt_allPaths;
    private javax.swing.JTextField txt_mindistance;
    // End of variables declaration//GEN-END:variables
}
